CREATE TABLE IF NOT EXISTS public.users
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "displayName" text COLLATE pg_catalog."default" NOT NULL,
    "passwordHash" text COLLATE pg_catalog."default" NOT NULL,
    "emailHash" text COLLATE pg_catalog."default" NOT NULL,
    "emailEncrypted" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp with time zone,
    "modifiedAt" timestamp with time zone,
    "role" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_unique_email UNIQUE ("emailHash")
)