CREATE TABLE IF NOT EXISTS public.jwt
(
    "sessionId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "refreshTokenHash" TEXT NOT NULL,
    "userId" INTEGER UNIQUE NOT NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "revokedAt" TIMESTAMPTZ,
    CONSTRAINT fk_login_sessions_user
        FOREIGN KEY ("userId")
        REFERENCES public.users ("id")
        ON DELETE CASCADE,
    CONSTRAINT login_unique_token UNIQUE ("refreshTokenHash"),
    CONSTRAINT login_unique_user UNIQUE ("userId")
)