CREATE TABLE IF NOT EXISTS public.recipes
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text COLLATE pg_catalog."default" NOT NULL,
    "userId" INTEGER NOT NULL,
    CONSTRAINT fk_recipe_user
        FOREIGN KEY ("userId")
        REFERENCES public.users ("id")
        ON DELETE CASCADE,
    CONSTRAINT recipe_unique_name UNIQUE ("name")
)