CREATE TABLE IF NOT EXISTS public.ingredients
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text COLLATE pg_catalog."default" NOT NULL,
    "category" integer NOT NULL,
    "defaultMeasurementType" integer NOT NULL,
    "description" text COLLATE pg_catalog."default",
    "createdAt" TIMESTAMPTZ NOT NULL,
    "createdBy" integer NOT NULL,
    "modifiedAt" TIMESTAMPTZ NOT NULL,
    "modifiedBy" integer NOT NULL
)
